spring:
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/cricket12 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
  
  